language: csharp
solution: BitcoinLib.sln
sudo: required

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty
    - mono: latest

script:
 - cd ./BitcoinLib
 - dotnet restore
 - dotnet build